# Generated by Django 4.2.3 on 2023-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='active_version',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
