# Generated by Django 4.2.3 on 2023-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_version_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(default=0, verbose_name='номер версии'),
        ),
    ]
