# Generated by Django 4.2.3 on 2023-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='active_version',
            field=models.BooleanField(verbose_name='признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
