# Generated by Django 4.2.3 on 2023-08-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_version_active_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('id',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
