# Generated by Django 4.2.3 on 2023-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='active_version',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='признак текущей версии'),
        ),
    ]
